def main_menu():
    print("1. Login")
    print("2. Exit")
    return input("Choose an option: ")

def super_admin_menu():
    print("1. Add System Administrator")
    print("2. View Logs")
    print("3. Add Consultant")
    print("4. Modify Consultant")
    print("5. Delete Consultant")
    print("6. Reset Consultant Password")
    print("7. Add Admin")
    print("8. Modify Admin")
    print("9. Delete Admin")
    print("10. Reset Admin Password")
    print("11. Backup System")
    print("12. Restore System")
    print("13. Add Member")
    print("14. Modify Member Information")
    print("15. Delete Member")
    print("16. Search Member")
    print("17. Display all users and roles")
    print("18. Exit to Main Menu")
    return input("Choose an option: ")

def system_admin_menu():
    print("1. Add Consultant")
    print("2. Modify Consultant")
    print("3. Delete Consultant")
    print("4. Reset Consultant Password")
    print("5. Backup System")
    print("6. Restore System")
    print("7. View Logs")
    print("8. Add Member")
    print("9. Modify Member Information")
    print("10. Delete Member")
    print("11. Search Member")
    print("12. Display all users and roles")
    print("13. Update Own Password")
    print("14. Exit to Main Menu")
    return input("Choose an option: ")

def consultant_menu():
    print("1. Register Member")
    print("2. Modify Member Information")
    print("3. Search Member")
    print("4. Update Own Password")
    print("5. Exit to Main Menu")
    return input("Choose an option: ")
